plugins:
  staff_alias_enabled:
    default: false
    client: true
    validator: "DiscourseStaffAlias::EnabledValidator"
  staff_alias_user_id:
    default: 0
    hidden: true
  staff_alias_username:
    default: ""
    client: true
    validator: "DiscourseStaffAlias::UsernameValidator"
  staff_alias_allowed_groups:
    default: "3"
    client: true
    type: group_list
